# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Brew Packages
      run: brew install swiftlint
    - name: SwiftLint
      run: swiftlint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
